### ISSUE TITLE
你要locket.lock 来执行命令

### ISSUE THREAD

**Issue by LunarstarFurry** [Himmelt/Locket#10]
我的服务器 Forge+Sponge 用了没办法给Permission给非OP
Command:/p global allow locket.lock
还有貌似ForgeEsssentials的Permissionlist里面也没有Locket的

**Comment by LunarstarFurry** [comment]
[告示牌锁］你需要权限 ⟨locket.lock⟩才能执行此命令

**Comment by LunarstarFurry** [comment]
Forge Essentials拒绝使用指令应该是显示英文的

**Comment by Himmelt** [comment]
> 我的服务器 Forge+Sponge 用了没办法给Permission给非OP
> Command:/p global allow locket.lock
> 还有貌似ForgeEsssentials的Permissionlist里面也没有Locket的

@LunarstarPony
我检查命令权限用的就是 `sender.hasPermission(permission)`，应该不会出问题。你用测试权限的指令测试一下玩家是否具有 `locket.lock` 权限，Forge Essentials 的命令我也不太熟。

你试一下手动添加到 Permissionlist 里呢？你有用什么Sponge的权限插件吗？Forge Essentials 并不是专门为Sponge写的吧。我建议还是用实现了 Sponge 权限系统的权限插件。

**Comment by LunarstarFurry** [comment]
ForgeEssentials跟Sponge是有兼容的好像

**Comment by LunarstarFurry** [comment]
我在安装的Sponge以后 Mod里面会出现一个ForgeEssentials跟Sponge的新mod

**Comment by LunarstarFurry** [comment]
我目前用起来只有OP有办法放 我如果把自己DeOP也会说没权限

**Comment by Himmelt** [comment]
> 我目前用起来只有OP有办法放 我如果把自己DeOP也会说没权限

@LunarstarPony 你装一个Sponge的权限插件，用权限插件管理权限，试试。

**Comment by LunarstarFurry** [comment]
有没有推荐的（

**Comment by Himmelt** [comment]
> 有没有推荐的（

[LuckPerms](https://ore.spongepowered.org/Luck/LuckPerms) 目前可能是最好用的权限插件了。

**Comment by LunarstarFurry** [comment]
nucleus呢ouo?

**Comment by Himmelt** [comment]
那个也还可以，我也就挺久之前用过。那么你问题解决了吗？是权限的问题吗？

**Comment by LunarstarFurry** [comment]
等等哈（

**Comment by LunarstarFurry** [comment]
啊 没看到（

**Comment by LunarstarFurry** [comment]
是说因为我用的是私服 这个能不能在没权限插件下运作啊（

**Comment by LunarstarFurry** [comment]
LuckPerms用了几天都没明白

**Comment by Himmelt** [comment]
> 是说因为我用的是私服 这个能不能在没权限插件下运作啊（

用这个附件里的版本，在 locket 的配置文件里，添加自定义权限映射 `locket.lock = ""` ，你自己测试吧。
```hocon
# 在停用插件时执行保存配置文件(前提是配置文件最近一次加载成功).
saveOnDisable = true
# 自定义权限映射表，用于自定义更改权限字符串.
permMap {
  locket.lock = ""
  admin = locket.admin
}
# 是否保护所有的实体方块(TileEntity).
protectTile = false
```
[SpongeViolet-2.4.1-SNAPSHOT-shadow.zip](https://github.com/Himmelt/Locket/files/3407259/SpongeViolet-2.4.1-SNAPSHOT-shadow.zip)
[Locket-1.1.8-SNAPSHOT.zip](https://github.com/Himmelt/Locket/files/3407262/Locket-1.1.8-SNAPSHOT.zip)

**Comment by LunarstarFurry** [comment]
好的 等等用看看

**Comment by LunarstarFurry** [comment]
好像没有用（

**Comment by Himmelt** [comment]
> 好像没有用（

那你只能尝试学习使用权限插件，要不就研究代码自行修改编译吧。

**Comment by Himmelt** [comment]
fixed by violet [update permission map](https://github.com/Himmelt/Violet/commit/116134ed8da542fd96ee19e5ade9e554f6a60699)
