### ISSUE TITLE
物品消失问题

### ISSUE THREAD

**Issue by ghost** [Himmelt/Locket#14]
此BUG由玩家回报，上锁的熔炉一段时间后，放在里头烧的矿物会消失
没上锁不会有这问题，好像也没有出现错误讯息

**Comment by Himmelt** [comment]
修复版本已发布 [https://ore.spongepowered.org/Himmelt/Locket/versions/1.2.1](https://ore.spongepowered.org/Himmelt/Locket/versions/1.2.1)

**Comment by ghost** [comment]
这插件有可能支援 UUID ? 
玩家更改ID后，原本的锁牌的方块没办法使用和破坏，必须请管理员替他们敲掉才行
