### ISSUE TITLE
这插件有可能支援 UUID ?

### ISSUE THREAD

**Issue by Himmelt** [Himmelt/Locket#15]
这插件有可能支援 UUID ? 
玩家更改ID后，原本的锁牌的方块没办法使用和破坏，必须请管理员替他们敲掉才行

_Originally posted by @GranTesoro86 in https://github.com/Himmelt/Locket/issues/14#issuecomment-572462728_

**Comment by Himmelt** [comment]
有可能的。时间应该不会拖太久。

**Comment by Himmelt** [comment]
[Locket-sponge-1.2.2.zip](https://github.com/Himmelt/Locket/files/4054363/Locket-sponge-1.2.2.zip)
@GranTesoro86 可否邀请你参与 UUID 的测试？如果你愿意帮助我测试，可将遇到的问题直接反馈在本 issue 中。

**Comment by ghost** [comment]
当然没问题 :)

**Comment by ghost** [comment]
我测试了一下没发现甚么严重问题
还有我建议改ID后的玩家和有锁牌的方块交互时，告示牌应该也更新他们的新ID
