### ISSUE TITLE
可能支援 GriefDefender 吗?

### ISSUE THREAD

**Issue by Himmelt** [Himmelt/Locket#18]
可能支援 GriefDefender 吗? 
原作者已经停止GriefPrevention的更新及维护
https://github.com/bloodmc/GriefDefender

_Originally posted by @GranTesoro86 in https://github.com/Himmelt/Locket/issues/5#issuecomment-574042926_

阔以！

**Comment by Himmelt** [comment]
@GranTesoro86

已支持 GriefDefender ，但是这个插件是收费的，只能靠你测试了。

[Locket-sponge-1.2.2.1.zip](https://github.com/Himmelt/Locket/files/4059125/Locket-sponge-1.2.2.1.zip)

**Comment by ghost** [comment]
经测试可以正常工作，
但发现了一个小BUG，如果玩家在方块上放置了两个空告示牌，接着将期中一个上锁，另一个空告示牌其他玩家也能通过指令上锁，会造成一个多个所有者的问题发生
