### ISSUE TITLE
玩家在方块上放置了两个空告示牌，接着将期中一个上锁，另一个空告示牌其他玩家也能通过指令上锁

### ISSUE THREAD

**Issue by Himmelt** [Himmelt/Locket#20]
经测试可以正常工作，
但发现了一个小BUG，如果玩家在方块上放置了两个空告示牌，接着将期中一个上锁，另一个空告示牌其他玩家也能通过指令上锁，会造成一个多个所有者的问题发生

_Originally posted by @GranTesoro86 in https://github.com/Himmelt/Locket/issues/18#issuecomment-574235630_

**Comment by Himmelt** [comment]
https://github.com/Himmelt/Locket/blob/d22e4bd4e6b43bbe4175534d3c4617fa97ac1623/SpongeLocket/src/main/java/org/soraworld/locket/command/CommandLocket.java#L74

原因是，检查访问对象错误，应该是检查访问告示牌所贴附的方块。

**Comment by Himmelt** [comment]
**@GranTesoro86**

已修复

[Locket-sponge-1.2.3.zip](https://github.com/Himmelt/Locket/files/4070542/Locket-sponge-1.2.3.zip)
[Locket-spigot-1.2.3.zip](https://github.com/Himmelt/Locket/files/4070543/Locket-spigot-1.2.3.zip)

**Comment by ghost** [comment]
测试过了  没问题
