### ISSUE TITLE
[suggestion]Why don't you complete the wiki to show the Locket's features? 

### ISSUE THREAD

**Issue by Tollainmear** [Himmelt/Locket#3]
if there is no user guide, people may not make choice to use locket？

**Comment by Himmelt** [comment]
多谢你的建议！
不过我比较业余，平时时间不多，这个插件还有一些问题没解决，还有一些问题是Sponge的问题。
wiki的话还是等有时间把插件完善之后再写吧。如果你有兴趣也可以提交代码。

**Comment by Himmelt** [comment]
I write a brief wiki today.

**Comment by Tollainmear** [comment]
OKOK 是友军 😆
