### ISSUE TITLE
Commands

### ISSUE THREAD

**Issue by Gunslito** [Himmelt/Locket#4]
Hi, how can I use your plugin? What are the commands for blocking chests? Thank you in advance!

**Comment by Himmelt** [comment]
I write a brief wiki,you can find it at [wiki](https://github.com/Himmelt/Locket/wiki).
This plugin is just like the "Lockette" plugin.
When I have spare time, I will finish this plugin and the wiki.

**Comment by Gunslito** [comment]
You're the best, will you update this for API7? Wonderful plugin

**Comment by Himmelt** [comment]
updated to API-7.1
